### ISSUE TITLE
Bug: prefix !default not being overridden

### ISSUE THREAD

**Issue by azuryte5** [Graupl/graupl#10]
## Summary

variables names other than graupl should exist.

**Comment by NickDJM** [comment]
So the way to do this (as discussed in-person) is to use `@forward` while configuring the base files.

https://sass-lang.com/documentation/at-rules/forward/#configuring-modules

```scss
// Import the file containing the variables you want to override.
@forward '@graupl/graupl/defaults' with (
  $prefix: 'custom',
);

// Import Graupl.
@forward '@graupl/graupl';

// Import your own theme...
```

I have created a PR with some documentation on this now as well.

**Comment by NickDJM** [comment]
Docs have been merged in.
