### ISSUE TITLE
Feat: Support for tables

### ISSUE THREAD

**Issue by azuryte5** [Graupl/graupl#24]
## Summary
Table functionality will be typically expected.

Add full support for base tables with options for responsive tables (including priority columns and/or scrolling) similar to how Bootstrap does it.

## Solution

- [x] Support for base table styles,
- [x] Support for responsive tables,
- [x] Support for row highlighting, alternating colours, borders, etc.,
- [x] Support for table captions and summaries,

**Comment by NickDJM** [comment]
@minorOffense You can follow table support here. I moved the information you had in your issue into this issue since it was made before yours.

**Comment by NickDJM** [comment]
The PR attached here is almost ready. I just need to clean up the component portion. It's in a rough testing state right now. Needs to be cleaned up, have variables added, run through some loops for colour variants, etc.
