### ISSUE TITLE
Feat: support for cards

### ISSUE THREAD

**Issue by azuryte5** [Graupl/graupl#63]
Default cards should have following properties

width (like 30ch) or max content 
height
padding
margin
flex direction? (default to be vertical or horizontal? perhaps or grid template 
background color
border width and colour
header
footer background color
card p font
card-img-direction (top, bottom, left, right)

**Comment by NickDJM** [comment]
Cards are implemented.

- Width/height is inherited from internal content and space provided.
- Padding can be controlled through --graupl-card-padding.
- Margin will not be implemented. Utility classes handle that.
- Flex direction isn't needed. Cards have and image and content section in a grid.
- Background/color can be controlle with --graupl-card-background/--graupl-card-color
- Border can be controlled with --graupl-card-border
- Header/footer/body background/color is inherited through the card. If it comes up as something we need we can look into separate variables for them.
- card p font is inherited by the root font weight.
- card-img-direction is a little over complicated. There is 1 variant class for cards: `.horiztonal` and then a variant on top of that `.left` and `.right`. I've never come across a case to have the image below the text. If it comes up we can re-evaluate.
